apiVersion: v1
kind: Service
metadata:
  name: flaskalk-svc
  labels:
    app: flaskalk
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    protocol: TCP
  selector:
    app: flaskalk
