FROM python:rc-alpine3.13

LABEL maintainer "j.melard@outlook.com"



RUN apk add --no-cache py3-pip 
RUN apk add --no-cache postgresql-libs  
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev  

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN  pip3 install -r requirements.txt --no-cache-dir 

COPY . /app

ENTRYPOINT [ "python3" ]

