version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    command: 'main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/


volumes:
  database-data:
