apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskalk-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskalk
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flaskalk
    spec:
      containers:
      - name: flaskalk
        image: melaen/flaskalk:multi
        imagePullPolicy: Always
        ports:
        - containerPort: 5000